http:
  services:
    file-browser:
      loadBalancer:
        servers:
          - url: "http://10.80.0.217:10187/"
  routers:
    file-browser:
      entryPoints:
        - https
      rule: "Host(`files.yourDomain.com`)"
      service: file-browser
      tls:
        certResolver: production
