http:
 # middlewares:
 #   add-admin:
 #     addPrefix:
 #       prefix: "/admin"
  middlewares:
    pihole-addprefix:
      addPrefix:
        prefix: /admin
    pihole-redirectregex:
      redirectRegex:
        regex: "https?://pihole.internal.internaldomain.com/$"
        replacement: "https://pihole.internal.internaldomain.com/admin/"
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
    
  services:
    file-browser-local:
      loadBalancer:
        servers:
          - url: "http://filebrowserIP:port/"
    plex-local:
      loadBalancer:
        servers:
          - url: "http://plexIP:port/"
    proxmox-local:
      loadBalancer:
        serversTransport: selfsigned
        servers:
          - url: "https://proxmoxIP:port/"
    portainer-local:
      loadBalancer:
        serversTransport: selfsigned
        servers:
          - url: "https://portainerIP:port/"
    special-local:
      loadBalancer:
        serversTransport: selfsigned
        servers:
          - url: "https://specialIP:port/"
    prometheus-local:
      loadBalancer:
        servers:
          - url: "http://serviceIP:port/"
    grafana-local:
      loadBalancer:
        servers:
          - url: "https://serviceIP:port/"
    truenas-local:
      loadBalancer:
        servers:
          - url: "https://serviceIP/"
    unifi-local:
      loadBalancer:
        serversTransport: selfsigned
        servers:
          - url: "https://serviceIP:port/"
    pihole-local:
      loadBalancer:
        servers:
          - url: "http://serviceIP/"
        passHostHeader: true
  routers:
    prometheus-local:
      entryPoints:
        - https
      rule: "Host(`prometheus.internal.internaldomain.com`)"
      service: prometheus-local
      tls:
        certResolver: production
    grafana-local:
      entryPoints:
        - https
      rule: "Host(`grafana.internal.internaldomain.com`)"
      service: grafana-local
      tls:
        certResolver: production
    truenas-local:
      entryPoints:
        - https
      rule: "Host(`truenas.internal.internaldomain.com`)"
      service: truenas-local
      tls:
        certResolver: production
    unifi-local:
      entryPoints:
        - https
      rule: "Host(`unifi.internal.internaldomain.com`)"
      service: unifi-local
      tls:
        certResolver: production
    pihole-local:
      entryPoints:
        - https
      rule: "Host(`pihole.internal.internaldomain.com`)"
      service: pihole-local
      tls:
        certResolver: production
      middlewares:
        - default-headers
        - pihole-redirectregex
#        - pihole-addprefix
        - https-redirectscheme

    file-browser-local:
      entryPoints:
        - https
      rule: "Host(`files.internal.internaldomain.com`)"
      service: file-browser-local
      tls:
        certResolver: production
    plex-local:
      entryPoints:
        - https
      rule: "Host(`plex.internal.internaldomain.com`)"
      service: plex-local
      tls:
        certResolver: production
    proxmox-local:
      entryPoints:
        - https
      rule: "Host(`proxmox.internal.internaldomain.com`)"
      service: proxmox-local
      tls:
        certResolver: production
    portainer-local:
      entryPoints:
        - https
      rule: "Host(`portainer.internal.internaldomain.com`)"
      service: portainer-local
      tls:
        certResolver: production
    special-local:
      entryPoints:
        - https
      rule: "Host(`special.internal.internaldomain.com`)"
      service: special-local
      tls:
        certResolver: production
  
# Skip verifying if a service has a self signed cert on it's internal IP.  
  serversTransports:
    selfsigned:
      insecureSkipVerify: True
