http: 
  services: 
    owncast-public: 
      loadBalancer: 
        servers: 
         # if the service is on an external host, 
         # we simply write ip or domain 
          - url: "http://owncastserverIP:8080/" 
  routers: 
    owncast-public: 
      entryPoints: 
        - https 
      # the web client will be accessible via any paths on the domain 
      # web.example.com 
      rule: "Host(`streams.publicdomain.com`)" 
      service: owncast-public 
      tls: 
        certResolver: production
