http: 
  services: 
    plex-public: 
      loadBalancer: 
        servers:  
          - url: "http://10.80.0.217:32400/" 
  routers: 
    plex-public: 
      entryPoints: 
        - https 
      rule: "Host(`plex.yourDomain.com`)" 
      service: plex-public 
      tls: 
        certResolver: production
