http: 
  services: 
    streamservice: 
      loadBalancer: 
        servers: 
         # if the service is on an external host, 
         # we simply write ip or domain 
          - url: "http://10.80.0.230:8069/" 
  routers: 
    streamservice: 
      entryPoints: 
        - https 
      # the web client will be accessible via any paths on the domain 
      # web.example.com 
      rule: "Host(`streams.yourDomain.com`)" 
      service: streamservice 
      tls: 
        certResolver: production
